name: flutter_wifi_p2p
description: Wifi P2P plugin for Flutter/Dart
version: 0.0.1
author: Thai Dinh Le

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  permission_handler: ^5.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.montefiore.thaidinhle.wifi.p2p.flutter_wifi_p2p
        pluginClass: FlutterWifiP2pPlugin
